[workspace]

resolver = "2"

members = [
    "sdk",
    "detectors",
    "compact-scanner",
    "tree-sitter-compact"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://www.openzeppelin.com/"
repository = "https://github.com/OpenZeppelin/midnight-security-detectors-sdk"

[workspace.dependencies]
midnight-security-detectors-sdk = { path = "./sdk", version = "0.0.1" }
midnight-security-detectors = { path = "./detectors", version = "0.0.1" }
compact-scanner = { path = "./compact-scanner", version = "0.0.1" }
tree-sitter-compact = { path = "./tree-sitter-compact" }
anyhow = "1.0.97"
tree-sitter = "0.25.1"

midnight-compact-parser = { path = "./parser", version = "0.0.1" }
