[workspace]

resolver = "2"

members = [
    "sdk",
    "parser",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
homepage = "https://www.openzeppelin.com/"
repository = "https://github.com/OpenZeppelin/midnight-security-rules-sdk"

[workspace.dependencies]
midnight-security-rules-sdk = { path = "./sdk", version = "0.0.1" }
midnight-compact-parser = { path = "./parser", version = "0.0.1" }
anyhow = "1.0.97"
